### ISSUE TITLE
Tracking issue: CD

### ISSUE THREAD

**Issue by DanielVoogsgerd** [epi-project/brane#100]
Now that CI (#77) is almost done, it is time to move on to CD as well. It does not seem to difficult, but we shall see.

To do:
- [x] Build central instance images
- [ ] Build worker instance images
- [x] Build binaries (natively)
- [ ] Build binaries (via emulation)

For progress see my fork and relevant triggered GitHub action runs, I am not creating a PR as of now as GitHub actions is basically a whole lot of testing by pushing.

**Comment by DanielVoogsgerd** [comment]
I think most parts are done already, from here it is mainly just finding a preferred trigger mechanism. @Lut99 what do would you like. What we could do is trigger a release when we push to a tag v<x>.<y>.<z> for example, but I'm not set on anything in particular.

**Comment by Lut99** [comment]
OK, I pushed epi-project/policy-reasoner#7566f131bfd65db2cd6775b579d59687a5162f6b. Seems like switching the dependency of the policy reasoner on Brane from `develop` -> `main`, running `cargo update` and then adding a missing feature is enough to make it work?

As for the other one: I'm not sure what the problem is... Can you give a little more detail?

**Comment by DanielVoogsgerd** [comment]
> OK, I pushed [epi-project/policy-reasoner@7566f13](https://github.com/epi-project/policy-reasoner/commit/7566f131bfd65db2cd6775b579d59687a5162f6b). Seems like switching the dependency of the policy reasoner on Brane from `develop` -> `main`, running `cargo update` and then adding a missing feature is enough to make it work? Can you try?

Yes it does, the worker images also compile now :) Another item off the checklist :)

> As for the other one: I'm not sure what the problem is... Can you give a little more detail?

Haha, it was more meant as a pointer for myself in order to remember what I was stuck on. 
If I use the `make.py --arch`` flag I am getting that error, I haven't really investigated it yet, so it might still be something obvious.

**Comment by Lut99** [comment]
The release mechanisms you mention are good! I don't mind doing a nightly/weekly release (let's say weekly or so), albeit just to check if the compilation works. And yeah, if you could only make it run if there are changes, that'd be great xD

RE the main release: I guess I prefer some manual trigger for now, but I am also fine with the manual trigger being the creation of a tag. Can that still work with giving some nice CHANGELOG messages? Or will we have to automate that, somehow?

**Comment by DanielVoogsgerd** [comment]
I think one can basically edit the release afterward to add the changelog contents, we could automate it without too much effort, but that would probably require that we split the changelog into separate files for each version, or we would need to do some parsing, not sure how "hard" that would be.

**Comment by Lut99** [comment]
I can live with that. Probably not worth it to go and write a parser for the CHANGELOG file xD

(DON'T do it Tim. _Don't do it._ You have enough parsers to write. :P)

**Comment by Lut99** [comment]
Also, to continue your question from <https://github.com/epi-project/brane/issues/77#issuecomment-2196788803>...

> That brings me to a semi-related question, I noticed that make.py does a cross compile for the macOS builds / windows builds. I am pretty sure using zig. Is there a reason for this?
> 
> Using CD we can just use the GitHub macOS runners to build the artifacts on the native platform. Or am I missing something here? And the same for windows of course. Different architectures should not be too much trouble as we can just compile those with a Cargo target afaik, and using cross otherwise.

Well, cross-compiling has always been a bit of a headache... xD Obviously, GitHub CI/CD didn't work before, so I was left compiling everything manually. Back when I just started, I looked at it, but it turned out that cross-compilation was a nightmare in Rust itself due to all the system libraries we depend on. Then I used to borrow mac mini's for a while to compile for M{1,2,3} architectures, but at some point that stopped too. Then I read somewhere that Zig could do the trick too and I can't remember if that worked xD but I guess so, if I didn't rollback.

Anyway ~ history aside, yeah I'm fine with whatever. I think just compiling natively on GitHub's runners is the way to go. The only reason we might need actual cross-compilation is if an aarch64 macbook wants to compile instance images for running on an x86/64 machine, which used to happen back in the days of Web Services and Cloud-Based Systems where the VMs were actually too low on storage to compile the images themselves. But I don't think it's a use-case we need to explicitly support anymore; once we have the release thing working, people can just download that _or_ the latest weekly images if necessary.

**Comment by DanielVoogsgerd** [comment]
Small update. This is coming together nicely, with the #102 issue fixed I can compile all required binaries on their respective platforms and all files are now collected together on a single runner. They still have to be renamed to their required naming scheme and we are done.

**Comment by Lut99** [comment]
Happy to hear that! Great work! :D

> What remains are release triggers. So a cron-style time based release and a release that triggers when a version tag is pushed.

I think those release triggers are fine.

> With regards to the download names. Shall we lift the exception of omitting the os/arch when there is only one available? I think providing this information in the filename is actually a good thing, and it is one less exception for me to add to CD.

As for the lifting the exception... yeah I guess it's fine. I originally didn't because I wanted to highlight that they're not _only_ for Linux, but rather OS-agnostic because they're only meant to run (in|as) a container. But that's not significant enough to make your life harder by having to take that into account xD

If you change the convention, though, you'd have to double-check `make.py`, `brane` and `branelet` to update them accordingly. From the top of my head, `make.py` shouldn't download them directly anymore (...I hope; so a double-check can't hurt); `branectl` downloads the (worker) instance images; and `brane` downloads `branelet` (that's all under the building of packages, `build_*.rs`).

> Furthermore I noticed that libbrane_cli is called brane_cli.dll on windows but libbrane_cli.dylib and libbrane.so on darwin and linux respectively. Is this correct behaviour?

Welcome to cross-platform dynamic libraries! :D Linux, for example, heavily relies on its particular naming scheme; I can link `libbrane_cli.so` with `-Lbrane_cli` because it automatically assumes it starts with `lib` and ends with `.so`. And I think the other OS'es have similar heavy assumptions on dynamic library names. But maybe you can double-check that, I've never really done manual linking in macOS or Windows.

I think that it's incorrect that Linux is called `libbrane.so` instead of `libbrane_cli.so`, though. Is that a typo? Else, maybe I did that because of naming conflicts of produces artefacts with the main `brane-cli` package. Note that `brane-cli-c` should produce `libbrane_cli_c.so` and such, of course, and while trying to remove the `_c` it turned out that some static libraries generated by Cargo suddenly collide. Maybe it had to do with that. But I say, just try to make it `libbrane_cli.so` and see if it breaks (compile both crates at the same time, just to be sure).

So: I don't mind in principle but I'm worried the OS'es can't handle the non-canonical names. But if you happen to know this is not an issue, feel free to homogenize them!

**Comment by DanielVoogsgerd** [comment]
> As for the lifting the exception... yeah I guess it's fine. I originally didn't because I wanted to highlight that they're not _only_ for Linux, but rather OS-agnostic because they're only meant to run (in|as) a container. But that's not significant enough to make your life harder by having to take that into account xD

Oh don't worry about me, that was more of a side effect. In general I am fine to create exceptions like this as long as they have some solid logic behind them, which this might be. But if I understand this correctly, if this is meant as something to run in a container, it would still be a container of a specific OS or arch right? If it was a prepared image I would agree as those could be "ran" on any system.

> If you change the convention, though, you'd have to double-check `make.py`, `brane` and `branelet` to update them accordingly. From the top of my head, `make.py` shouldn't download them directly anymore (...I hope; so a double-check can't hurt); `branectl` downloads the (worker) instance images; and `brane` downloads `branelet` (that's all under the building of packages, `build_*.rs`).

Yeah this has to be done before we can merge as well. I will add it as a checklist item

> So: I don't mind in principle but I'm worried the OS'es can't handle the non-canonical names. But if you happen to know this is not an issue, feel free to homogenize them!

Oh hell no, I have no clue :sweat_smile: I have done close to zero linking on anything but linux so I will gladly stay compliant with I know what works.

**Comment by Lut99** [comment]
> Oh don't worry about me, that was more of a side effect. In general I am fine to create exceptions like this as long as they have some solid logic behind them, which this might be. But if I understand this correctly, if this is meant as something to run in a container, it would still be a container of a specific OS or arch right? If it was a prepared image I would agree as those could be "ran" on any system.

Yes. So here's a little leeway for interpretation. Maybe you're right in that the binaries are still all Linux x86/64 or Arm64, even when running in a container. So maybe we can add a `-linux` to `branelet`, that seems fair. But the images (in the `tar.gz`) are in that sense "truly" OS-independent, as they encapsulate the OS they are built for. So probably it's best to leave the OS out for those.

On an aside, note that Brane still depends on libc one way or another. So if you're building the images on a "too updated" Linux distribution (e.g., Arch), then you're lose compatibility with all older GLIBC versions. And even worse, I thought that non-rolling releases (such as Debian) do not update GLIBC between versions. So if you're building on Debian(-based), choose a version that is old enough to support a nice range of OS'es :) (e.g., 20.04+ or something).
