### ISSUE TITLE
Policy reasoner nice-to-haves

### ISSUE THREAD

**Issue by Lut99** [epi-project/brane#174]
This issue tracks some features related to the policy reasoner that are nice-to-have. Or at least, which won't be our immediate focus.

Things left to do are:
- [ ] Add metadata definitions to Brane containers
- [ ] Add metadata definitions to Brane datasets
- [ ] Add proper user identification/authorisations
    - This is clearly a much bigger project, but necessary for proper functionality with the reasoner.
- [ ] Add options to sign workflows / metadata for verification
