### ISSUE TITLE
Functions as data

### ISSUE THREAD

**Issue by Lut99** [epi-project/brane#177]
Another branch encountered while pruning old ones. `functions-as-data` was part of the effort to get rid of special treatment for containers, and instead treat them as regular old datasets with an `executable`-tag.

This is a highly desired feature, because we get container policy enforcement for free as a function of data enforcement. Further, data scientists can then also independently push non-sensitive (test) datasets to the central node instead of having to go to a worker. However, due to time constraints, the work never progressed beyond the first step, which is including the central registry as a potential location to source datasets from in the compiler (`brane-ast`) and the VM (`brane-exe`).

Because of the little work, and the fact this branch is a meager 237 commits behind at the time of writing, it has been deleted. Instead, this issue serves to document its goal and to potentially act as a tracking issue the day that the work ever becomes relevant again.

Things to do (draft):
- [ ] Extend the VM to allow the central location as potential data source
- [ ] #65 (in order to communicate to Brane that some data is executable)
- [ ] Change the central registry to be `brane-reg`-compatible and host data
- [ ] Change the executor to homogenize the treatment of containers and data
