### ISSUE TITLE
Migrate from `make.py` to `Makefile`

### ISSUE THREAD

**Issue by Lut99** [epi-project/brane#194]
Nothing of this will be a big surprise :) but just to keep track of things to do to move build systems.

- [ ] Add additional binary targets to `Makefile`
  
  Specifically, `brane-cc` (`branec`) and `brane-cli-c` (`libbrane_cli`).
- [ ] Add target for running tests to `Makefile`
  
  Ideally, I'd like to use this target in the appropriate GH Action too to be sure that it's easy to run local tests and get the same result online.
- [ ] Add tests for the build system in GH Actions
  
  I'm quite surprised our broken `make.py` breaks none of our workflows! It's good that we're not using it in most runs :) but we probably should have a run that just builds the framework using the script so we can catch any problems with it earlier.
- [ ] Update the documentation to use `Makefile`
- [ ] Remove (broken|obsolete) `make.py`

**Comment by DanielVoogsgerd** [comment]
Yeah, all the above seems reasonable.

The one I want to scratch for our builds is the storage location of the artifacts. Currently, they are stored in `target/{debug,release}`, however these directories are often cluttered with a lot of partial compilation files.

> Add tests for the build system in GH Actions
>       I'm quite surprised our broken `make.py` breaks none of our workflows! It's good that we're not using it in most runs :) but we probably should have a run that just builds the framework using the script so we can catch any problems with it earlier.

This is because we just used normal compilation as a proxy for the docker buildx images, but now that we have the Makefile I think we can transition quite easily to those instead.

**Comment by Lut99** [comment]
Hmm. Right. `build` and `target` already start to conflate a little conceptually. So maybe better to stick after all.

But maybe keep it in mind until something obvious presents itself?
